/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ERC20Balance: (() => {
      return defineComponent(
        world,
        {
          token: RecsType.String,
          account: RecsType.String,
          amount: RecsType.BigInt,
        },
        {
          metadata: {
            name: "ERC20Balance",
          },
        }
      );
    })(),
  };
}
